
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mas.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-12T23:26:36.835+05:30
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "WeatherServiceService",
                      portName = "WeatherServicePort",
                      targetNamespace = "http://service.mas.com/",
                      wsdlLocation = "http://localhost:8080/ApacheCXFWeatherService/services/WeatherServicePort?wsdl",
                      endpointInterface = "com.mas.service.WeatherService")
                      
public class WeatherServiceImpl implements WeatherService {

    private static final Logger LOG = Logger.getLogger(WeatherServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.mas.service.WeatherService#getWeatherByCityId(int  arg0 )*
     */
    public com.mas.service.Weather getWeatherByCityId(int arg0) { 
        LOG.info("Executing operation getWeatherByCityId");
        System.out.println(arg0);
        try {
            com.mas.service.Weather _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.mas.service.WeatherService#getTempByWeather(com.mas.service.Weather  arg0 )*
     */
    public int getTempByWeather(com.mas.service.Weather arg0) { 
        LOG.info("Executing operation getTempByWeather");
        System.out.println(arg0);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
