package com.mas.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-12T23:26:37.023+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.mas.com/", name = "WeatherService")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherService {

    @WebMethod
    @RequestWrapper(localName = "getWeatherByCityId", targetNamespace = "http://service.mas.com/", className = "com.mas.service.GetWeatherByCityId")
    @ResponseWrapper(localName = "getWeatherByCityIdResponse", targetNamespace = "http://service.mas.com/", className = "com.mas.service.GetWeatherByCityIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mas.service.Weather getWeatherByCityId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTempByWeather", targetNamespace = "http://service.mas.com/", className = "com.mas.service.GetTempByWeather")
    @ResponseWrapper(localName = "getTempByWeatherResponse", targetNamespace = "http://service.mas.com/", className = "com.mas.service.GetTempByWeatherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getTempByWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mas.service.Weather arg0
    );
}
