package com.mas.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-11-11T18:17:17.755+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.mas.com/", name = "CalService")
@XmlSeeAlso({ObjectFactory.class})
public interface CalService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.mas.com/", className = "com.mas.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.mas.com/", className = "com.mas.service.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
