
package com.mas.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Nov 12 20:44:13 IST 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getTempByWeather", namespace = "http://service.mas.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTempByWeather", namespace = "http://service.mas.com/")

public class GetTempByWeather {

    @XmlElement(name = "arg0")
    private com.mas.service.Weather arg0;

    public com.mas.service.Weather getArg0() {
        return this.arg0;
    }

    public void setArg0(com.mas.service.Weather newArg0)  {
        this.arg0 = newArg0;
    }

}

