
package com.mas.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Nov 12 20:44:13 IST 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getWeatherByCityId", namespace = "http://service.mas.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getWeatherByCityId", namespace = "http://service.mas.com/")

public class GetWeatherByCityId {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

